name: Generate Manifest Komik

on:
  workflow_dispatch:
    inputs:
      max_komik:
        description: 'Maximum number of Komik to scrape (unused here)'
        required: false
        default: '10'
  schedule:
    - cron: '*/5 * * * *'  # setiap 5 menit

jobs:
  run-script:
    runs-on: ubuntu-latest

    # ====== SEKALI TULIS SEMUA ENV/SECRETS DI SINI ======
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      BUCKET_NAME:  ${{ secrets.BUCKET_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies (with fallback)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt tidak ditemukan — install paket minimum."
            # Minimal libs yang dibutuhkan script ini
            pip install supabase python-dotenv
          fi

      - name: Run Generate Manifest Script
        run: python generate-manifest.py
