name: Generate Manifest Komik

on:
  workflow_dispatch:
  schedule:
    # Jalan setiap hari jam 21:00 WIB (14:00 UTC)
    - cron: '0 21 * * *'
    # OPTIONAL: debug sementara, jalan setiap 5 menit (hapus setelah beres)
    # - cron: '*/5 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      BUCKET_NAME:  ${{ secrets.BUCKET_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Print timestamps (UTC & WIB)
        run: |
          echo "UTC now      : $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "Asia/Jakarta : $(TZ=Asia/Jakarta date '+%Y-%m-%d %H:%M:%S')"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies (with fallback)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt tidak ditemukan — install paket minimum."
            pip install supabase python-dotenv
          fi

      - name: Run Generate Manifest Script
        run: python generate-manifest.py
